name: Test boolean inputs

on:
  workflow_dispatch:

jobs:
  display:
    runs-on: ubuntu-latest

    steps:
      - name: Display branch workflow
        shell: bash
        run: |
          echo "Branch : ${{ github.ref }}"