name: Write 2 messages in PR

on:
  pull_request:


jobs: 
  write-pr-message:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
      with:
        script: |
          const repo = context.repo.repo;
          const owner = context.repo.owner;
          const issue_number = ${{ inputs.pr-number }};
          
          if (!issue_number) {
            core.setFailed('Missing issue number. This value must be provided with the parameter pr-number when used by a workflow without a pull_request context');
          }

          const messagePrefix = "🚀 This pull request has been deployed to: "
          const message = messagePrefix + "https://swbengine-application-api-alz.schneider-electric.com/switchboard-editor-api/swagger-ui/index.html";

          const wasDeployed = "${{ inputs.url }}".startsWith("https");

          const comments = await github.rest.issues.listComments({
            owner,
            repo,
            issue_number,
          });

          var update = false;
          for (const comment of comments.data) {
            if (comment.body.startsWith(messagePrefix)) {
              update= true;

              if (wasDeployed) {
                github.rest.issues.updateComment({
                  owner,
                  repo,
                  comment_id: comment.id,
                  body: message,
                });
              } else {
                github.rest.issues.deleteComment({
                    owner,
                    repo,
                    comment_id: comment.id
                });
              }
              break;
            }
          }


          if (wasDeployed && !update) {
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: message,
            });
          }
    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
      with:
        script: |
          const repo = context.repo.repo;
          const owner = context.repo.owner;
          const issue_number = ${{ inputs.pr-number }};
          
          if (!issue_number) {
            core.setFailed('Missing issue number. This value must be provided with the parameter pr-number when used by a workflow without a pull_request context');
          }

          const messagePrefix = "🚀 This pull request has been deployed to: "
          const message = messagePrefix + "https://swbengine-application-api-alz.schneider-electric.com/switchboard-engine-api/swagger-ui/index.html";

          const wasDeployed = "${{ inputs.url }}".startsWith("https");

          const comments = await github.rest.issues.listComments({
            owner,
            repo,
            issue_number,
          });

          var update = false;
          for (const comment of comments.data) {
            if (comment.body.startsWith(messagePrefix)) {
              update= true;

              if (wasDeployed) {
                github.rest.issues.updateComment({
                  owner,
                  repo,
                  comment_id: comment.id,
                  body: message,
                });
              } else {
                github.rest.issues.deleteComment({
                    owner,
                    repo,
                    comment_id: comment.id
                });
              }
              break;
            }
          }


          if (wasDeployed && !update) {
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: message,
            });
          }
